# Used to get an access token given an authorization key
POST {{baseUrl}}/token?grant_type=client_credentials
Authorization: Basic {{authorization}}

###

GET {{baseUrl}}/t/nubentos.com/ncovapi/1.0.0/cases
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/casesSuspected
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/casesConfirmed
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/deaths
Accept: application/json
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/recovered
Accept: application/json
Authorization: Bearer {{accessToken}}